cart_app/urls.py
from . import views
from django.urls import path
app_name='cart_app'

urlpatterns=[
    path(' ',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
   path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
   path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')
    
]

ecom_app/urls.py
from . import views
from django.urls import  path
app_name = 'ecom_app'

urlpatterns = [
   path('',views.allProCat,name='allProCat'),
   path('<slug:c_slug>/',views.allProCat,name='products_by_category'),
   path('<slug:c_slug>/<slug:product_slug>',views.proDetail,name='prodCatdetail'),
]

ecom_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecom_app.urls')),
    path('search_app/',include('search_app.urls')),
    path('cart_app/',include('cart_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import  path
from . import views


app_name = 'search_app'
urlpatterns = [
    path('search/',views.SearchResult,name='SearchResult'),
]

cart_app/models.py
from django.db import models
from ecom_app.models import Product
# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)
    class Meta:
        db_table ='Cart'
        ordering = ['date_added']
    def __str__(self):
        return {}.format(self.cart_id)
    
class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default = True)
    class Meta:
        db_table = 'CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return {}.format(self.product)

ecom_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category',blank=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
        
    # def get_url(self):
    #     return reverse('ecom_app:products_by_category',args = [self.slug])
    def get_url(self):
        return reverse('ecom_app:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product',blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
        
    def get_url(self):
        return reverse('ecom_app:prodCatdetail', args=[self.category.slug,self.slug])
    
    def __str__(self):
        return '{}'.format(self.name)

search_app/models.py
from django.db import models

# Create your models here.

cart_app/views.py
from itertools import product
from tkinter import NO
from django.shortcuts import get_object_or_404, redirect, render
from cart_app.models import Product
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id = _cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id = _cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product = product,cart = cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product,quantity = 1,cart=cart)
        cart_item.save()
    return redirect('cart_app:cart_detail')

def cart_detail(request,total = 0,counter = 0,cart_items = None):
    cart = None
    try:
        cart=Cart.objects.get(cart_id = _cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',{'cart_items': cart_items, 'total': total, 'counter': counter})


def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id = _cart_id(request))
    product = get_object_or_404(Product,id = product_id)
    cart_item = CartItem.objects.get(product = product,cart = cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart_app:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id = _cart_id(request))
    product = get_object_or_404(Product,id = product_id)
    cart_item = CartItem.objects.get(product = product,cart = cart)
    cart_item.delete()
    return redirect('cart_app:cart_detail')

ecom_app/views.py
# from django.http import  HttpResponse
# from django.shortcuts import get_object_or_404, render

# from . models import Category, Product

# # Create your views here.

# # def index(request):
# #     return HttpResponse("Hi hello welcome...")

# def allProCat(request,c_slug=None):
#     c_page=None
#     products=None
#     if c_slug is not None:
#         c_page = get_object_or_404(Category,slug = c_slug)
#         products = Product.objects.all().filter(category=c_page,available=True)
#     else:
#         products = Product.objects.all().filter(available=True)
#         return render(request,"category.html",{'category':c_page,'products':products})        

from itertools import product
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from . models import Category, Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

def allProCat(request, c_slug=None):
    c_page = None
    products_list = None

    if c_slug is not None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.filter(category = c_page, available=True)
    else:
        products_list = Product.objects.filter(available=True)
    paginator = Paginator(products_list,6)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, "category.html", {'category': c_page, 'products': products})


def proDetail(request,c_slug,product_slug):
    
    try:
        product = Product.objects.get(category__slug = c_slug,slug = product_slug)
    except Exception as e:
        raise e
    
    return render(request,'product.html',{'product':product})

search_app/views.py
from django.shortcuts import render
from ecom_app.models import Product
from django.db.models import Q

# Create your views here.

def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains = query)|Q(description__contains = query))
    return render(request,'search.html',{'query':query,'products':products})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/1b99dd44bf.js " crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% include 'header.html' %}
        {% include 'navbar.html' %}
    
        {% block content %}{% endblock %}
    </div>
            {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>
    
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    This is the cart page proceed to review your items and place the order.
{% endblock %}

{% block title %}
    CART-page
{% endblock %}

{% block content %}
    {% if not cart_items %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my-title">
                    YOUR SHOPPING CART IS EMPTY
                </h1>
                <p class="text-center">
                    Please Check <a href="{% url 'ecom_app:allProCat'%}">Here</a> to Continue Shopping            
                </p>     
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my-title">
                    YOUR SHOPPING CART
                </h1>
            </div>
            <br>
            <div class="row mx-auto">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table my_custom_table">
                        <thead class="my_custom_thead">
                            <tr>
                                <th colspan="5">
                                    YOUR ITEMS
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cart_item in cart_items %}
                                <tr>
                                    <td>
                                        <a href="{{cart_item.product.get_absolute_url}}"><img src="{{cart_item.product.image.url}}" alt="cart image" style="width: 150px; height: 150px;"> </a>
                                    </td>
                                    <td class="text-left">
                                        <b>{{cart_item.product.name}}</b>
                                        <br>
                                        ID:{{cart_item.product.id}}
                                        <br>
                                        PRICE: RS.{{cart_item.product.price}}
                                        <br>
                                        Qty: {{ cart_item.quantity }} * {{ cart_item.product.price }}

                                    </td>
                                    <td>
                                        ${{cart_item.sub_total}}
                                    </td>
                                   {% if cart_item.quantity < cart_item.product.stock %}
                                    <td>
                                        <a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-plus custom_icon"></i></a>
                                        &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                                        &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash custom_icon"></i></a>
                                    </td>
                                    {% else %}
                                    <td>
                                       
                                            &nbsp;<a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-plus custom_icon"></i></a>
                                            &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                                            &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash custom_icon"></i></a>
                                        
                                    </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                        <tr>
                            <th>
                                Checkout
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                Please review your shopping cart item before proceeding with the order payment.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                YOUR TOTAL IS : <STRONG>{{total}}</STRONG>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="mx-auto">
                    <a href="{% url 'ecom_app:allProCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a><br>
                    <a href="{% url 'ecom_app:allProCat' %}" class="btn btn-success btn-block my_custom_button">PROCEED TO PAY  </a>
                </div>
                <br>
                <br>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock%}

templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}

    {% if category %}

        {{category.description|truncatewords:155}}

    {% else %}

        <h5>WELCOME TO AYRIN FASION WORLD </h5>

    {% endif %}

{% endblock %}

{% block title %}

    {% if category %}

        {{category.name}}

    {% else %}

        AYRIN FASION SHOP

    {% endif %}

{% endblock %}

<div class="container">
{% block content %}

    {% if category %}
        <div>
            <div class="row my_row_class">
                <div class="mx-auto">
                    <p><a href="{% url 'ecom_app:allProCat' %}">OUR PRODUCT COLLECTIONS </a></p>
                </div>
            </div>
        </div>
    {% endif %}

    {% if category %}
        <div class="mx-auto">
            <img class="my_image" src="{{category.image.url}}" alt="{{category.name }}">
        </div>
        <br>
        <div>
            <h1 class="text-center my_title">{{category.name}}</h1>
            <p class="text-justify">{{category.description}}</p>
        </div>
    {% else %}
        <div>
            <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="OUR PRODUCTS" width="1520px">
        </div>
        <br>
        <div>
            <h1 class="text-center my_title"><b>Our COLLECTIONS</b></h1>
            <p class="text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
            </p>
        </div>
    {% endif %}

<div class="container">
    <div class="row mx-auto">
        {% for product in products.object_list %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                <div class="card text-center">
                    <a href="{{ product.get_url }}">
                        <div class="my-image-wrapper">
                            <img class="card-img-top my-image1" src="{{ product.image.url }}" alt="{{ product.name }}">
                        </div>
                    </a>
                    <div class="card-body">
                        <h4 class="card-title">{{ product.name }}</h4>
                        <p class="card-price">{{ product.price }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

    
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>

</div>
{% endblock %}

templates/footer.html
<div class="footer navbar-fixed-bottom my-footer">
    <p> &copy;AYRIN FASION STORE PVT LIMITED . ALL RIGHTS RESERVED</p>
</div>

templates/header.html
{% load static %}
<header>
    <center>
      <a href="{% url 'ecom_app:allProCat' %}"><img src="{% static 'img/logo3.png' %}" alt="logoimage" width="250px" height="250px"></a
    </center>
</header>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top" style="background-color: rgb(9, 5, 10); ">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="#" style="color: white;" ><i class="fa-solid fa-house"></i> HOME </a>
          </li>

          <li class="nav-item dropdown {% if 'ecom_app' in request.path %}active{% endif %}">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: white;">
              SHOP
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'ecom_app:allProCat' %}">ALL PRODUCTS</a></li>
              {% for cat in Links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
            </ul>
          </li>
          {% if item_count > 0 %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'cart_app:cart_detail' %}" style="color: white;"> &nbsp; &nbsp;<i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
          <button class="btn btn-outline-light" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
      </div>
    </div>
  </nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{ product.description|truncatewords:155 }}
{% endblock %}

{% block title %}
    {% if category %}
        {{ product.name }} - AYRIN STORE
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container">
        <div>
            <p><a href="{% url 'ecom_app:allProCat' %}">HOME</a> | <a href="{{ product.category.get_url }}">{{ product.category }}</a> | {{ product.name }}</p>
        </div>
    </div>
    <br>

    <div class="product-details-container">
        <div class="product-image">
            <img src="{{ product.image.url }}" alt="{{ product.name }}" width="250" height="250">
        </div>

        <div class="product-info">
            <h1>{{ product.name }}</h1>
            <p>{{ product.price }}</p>
            <p class="section-title">PRODUCT DESCRIPTION</p>
            <p>{{ product.description }}</p>

            {% if product.stock <= 0 %}
                <p class="out-of-stock"><b> Out of Stock </b></p>
            {% else %}
                <a href="{% url 'cart_app:add_cart' product.id %}" class="add-to-cart-btn">Add to Cart</a>
            {% endif %}
            
        </div>
    </div>
    <br>
    <br>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}

   WE HAVE VARIETY OF PRODUCTS.

{% endblock %}

{% block title %}
SEARCH
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for : <b>{{query}}</b></p>
</div>
<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                <div class="card text-center">
                    <a href="{{ product.get_url }}">
                        <div class="my-image-wrapper">
                            <img class="card-img-top my-image1" src="{{ product.image.url }}" alt="{{ product.name }}">
                        </div>
                    </a>
                    <div class="card-body">
                        <h4 class="card-title">{{ product.name }}</h4>
                        <p class="card-price">{{ product.price }}</p>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="row mx-auto">
                <p class="text-center my_search_text">
                    0 RESULT FOUND
                </p>
            </div>
        {% endfor %}
      </div>
    </div>
{% endblock %}